-- MySQL Script generated by MySQL Workbench
-- Wed Jul  5 17:26:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ordem de Serviço` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `idOrdem de Serviço` INT NOT NULL,
  `Numero do Serviço` INT NULL,
  `Orçamento(valor)` INT NOT NULL,
  `Data de entrega` DATE NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOrdem de Serviço`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Data de entrega_UNIQUE` ON `mydb`.`Ordem de Serviço` (`Data de entrega` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Veículo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Veículo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Veículo` (
  `idVeículo` INT NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Cor` VARCHAR(45) NOT NULL,
  `Placa` INT NOT NULL,
  `Ano` INT NOT NULL,
  PRIMARY KEY (`idVeículo`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Placa_UNIQUE` ON `mydb`.`Veículo` (`Placa` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Ano_UNIQUE` ON `mydb`.`Veículo` (`Ano` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Veículo_idVeículo` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Veículo_idVeículo`),
  CONSTRAINT `fk_Cliente_Veículo1`
    FOREIGN KEY (`Veículo_idVeículo`)
    REFERENCES `mydb`.`Veículo` (`idVeículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Cliente_Veículo1_idx` ON `mydb`.`Cliente` (`Veículo_idVeículo` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Mecânico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mecânico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Mecânico` (
  `idMecânico` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Salário` VARCHAR(45) NOT NULL,
  `Especialidade` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `Código` INT NULL,
  `Veículo_idVeículo` INT NOT NULL,
  PRIMARY KEY (`idMecânico`),
  CONSTRAINT `fk_Mecânico_Veículo1`
    FOREIGN KEY (`Veículo_idVeículo`)
    REFERENCES `mydb`.`Veículo` (`idVeículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Mecânico_Veículo1_idx` ON `mydb`.`Mecânico` (`Veículo_idVeículo` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Especialidade_UNIQUE` ON `mydb`.`Mecânico` (`Especialidade` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Endereço_UNIQUE` ON `mydb`.`Mecânico` (`Endereço` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pessoa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idpessoa` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Mecânico_idMecânico` INT NOT NULL,
  PRIMARY KEY (`idpessoa`, `Cliente_idCliente`, `Mecânico_idMecânico`),
  CONSTRAINT `fk_Pessoa_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Mecânico1`
    FOREIGN KEY (`Mecânico_idMecânico`)
    REFERENCES `mydb`.`Mecânico` (`idMecânico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Pessoa_Cliente_idx` ON `mydb`.`Pessoa` (`Cliente_idCliente` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Pessoa_Mecânico1_idx` ON `mydb`.`Pessoa` (`Mecânico_idMecânico` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Município`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Município` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Município` (
  `idMunicípio` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Região` VARCHAR(45) NOT NULL,
  `Pessoa_idpessoa` INT NOT NULL,
  `Pessoa_Cliente_idCliente` INT NOT NULL,
  `Pessoa_Mecânico_idMecânico` INT NOT NULL,
  PRIMARY KEY (`idMunicípio`, `Pessoa_idpessoa`, `Pessoa_Cliente_idCliente`, `Pessoa_Mecânico_idMecânico`),
  CONSTRAINT `fk_Município_Pessoa1`
    FOREIGN KEY (`Pessoa_idpessoa` , `Pessoa_Cliente_idCliente` , `Pessoa_Mecânico_idMecânico`)
    REFERENCES `mydb`.`Pessoa` (`idpessoa` , `Cliente_idCliente` , `Mecânico_idMecânico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Nome_UNIQUE` ON `mydb`.`Município` (`Nome` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Região_UNIQUE` ON `mydb`.`Município` (`Região` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Município_Pessoa1_idx` ON `mydb`.`Município` (`Pessoa_idpessoa` ASC, `Pessoa_Cliente_idCliente` ASC, `Pessoa_Mecânico_idMecânico` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Veiculo para ordem de serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Veiculo para ordem de serviço` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo para ordem de serviço` (
  `Veículo_idVeículo` INT NOT NULL,
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  `Ordem de Serviço_OS_idOS` INT NOT NULL,
  PRIMARY KEY (`Veículo_idVeículo`, `Ordem de Serviço_idOrdem de Serviço`, `Ordem de Serviço_OS_idOS`),
  CONSTRAINT `fk_Veículo_has_Ordem de Serviço_Veículo1`
    FOREIGN KEY (`Veículo_idVeículo`)
    REFERENCES `mydb`.`Veículo` (`idVeículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veículo_has_Ordem de Serviço_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço`)
    REFERENCES `mydb`.`Ordem de Serviço` (`idOrdem de Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Veículo_has_Ordem de Serviço_Ordem de Serviço1_idx` ON `mydb`.`Veiculo para ordem de serviço` (`Ordem de Serviço_idOrdem de Serviço` ASC, `Ordem de Serviço_OS_idOS` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Veículo_has_Ordem de Serviço_Veículo1_idx` ON `mydb`.`Veiculo para ordem de serviço` (`Veículo_idVeículo` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Peça`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Peça` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Peça` (
  `idPeça` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Valor` INT NOT NULL,
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  PRIMARY KEY (`idPeça`),
  CONSTRAINT `fk_Peça_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço`)
    REFERENCES `mydb`.`Ordem de Serviço` (`idOrdem de Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Valor_UNIQUE` ON `mydb`.`Peça` (`Valor` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Peça_Ordem de Serviço1_idx` ON `mydb`.`Peça` (`Ordem de Serviço_idOrdem de Serviço` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Serviço` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço` (
  `idServiço` INT NOT NULL,
  `Mão de Obra(valor)` VARCHAR(45) NOT NULL,
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  PRIMARY KEY (`idServiço`),
  CONSTRAINT `fk_Serviço_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço`)
    REFERENCES `mydb`.`Ordem de Serviço` (`idOrdem de Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Mão de Obra_UNIQUE` ON `mydb`.`Serviço` (`Mão de Obra(valor)` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Serviço_Ordem de Serviço1_idx` ON `mydb`.`Serviço` (`Ordem de Serviço_idOrdem de Serviço` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
